repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
-  repo: https://github.com/kynan/nbstripout
   rev: 0.9.0
   hooks:
    -   id: nbstripout